### ISSUE TITLE
URL parameter values stripped when `exclude` option not specified

### ISSUE THREAD

**Issue by joshea0** [joshea0/caching-proxy#1]
## Problem description

when the `exclude` option is not specified, `Cache.getId` strips parameter values from the `requestUrl`, causing the cache to incorrectly return a cached response when given different parameter values for the same URL due to the parameter values not being included when computing the hash.

The problem occurs inside `Cache.getId`:

this.exclude is `[ '' ]`

Which causes this loop to strip the values from all parameters:
```js
for(var i=0; i<this.exclude.length; i++){
    var regex = new RegExp(this.exclude[i]+'\=[a-zA-Z0-9\\-\\_]+[\&]*','ig')
    requestUrl = requestUrl.replace(regex, '');
}
```
due to regex becoming `/=[a-zA-Z0-9\-\_]+[&]*/gi` on the single loop iteration

this causes a requestUrl such as :
```
GET http://some-cool-api.com/query?start=0&count=5
```
to become:
```
GET http://some-cool-api.com/query?startcount
```

Which means the cache will incorrectly map these two URLs to the same cache entry:
* `http://some-cool-api.com/query?start=0&count=5`
* `http://some-cool-api.com/query?start=100&count=5`

## Troubleshooting & workaround

My script for starting the caching-proxy was originally:
```js
var CachingProxy=require('caching-proxy');

var proxy = new CachingProxy({
   port: 9090,
   dir: '/home/vagrant/proxycache/data/cached-data',
});
```

When I changed it to specify an exclude option, the issue went away:
```js
var CachingProxy=require('caching-proxy');

var proxy = new CachingProxy({
   port: 9090,
   dir: '/home/vagrant/proxycache/data/cached-data',
   exclude: 'rand,cache-buster'
});
```

## Fix

My simple fix for this issue (without having to specify the `exclude` option as a workaround) was to change the problematic loop to check the parameter key coming from `this.exclude` to ensure the regex stripping is only performed on strings with length > 0:
```js
for(var i=0; i<this.exclude.length; i++){
    if (this.exclude[i].length > 0) {
      var regex = new RegExp(this.exclude[i]+'\=[a-zA-Z0-9\\-\\_]+[\&]*','ig')
      requestUrl = requestUrl.replace(regex, '');
    }
}
```

**Comment by chwagssd** [comment]
Great find - thanks for helping with this update @joshea0 ! And keep up the good work, wonderful how you explained the issue.
